### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by demianh** [demianh/my-browser#3]
Issue to track some things that need to be done:

- [ ] br tags
- [ ] images
- [ ] text within inline elements (line boxes?)
- [ ] correct line height calculation
- [ ] draw borders
- [ ] html entities
- [ ] inline-block elements
- [ ] block elements inside inline elements
